### ISSUE TITLE
flint_abort does not exist in flint library

### ISSUE THREAD

**Issue by rickyefarr** [flintlib/arb#178]
I decided to build Arb in the new linux subsystem of Windows and when I did a make check, I got the following:

 CC   ../build/fmpr/test/t-abs_bound_le_2exp_fmpz
/tmp/ccyuIK39.o: In function `main':
t-abs_bound_le_2exp_fmpz.c:(.text.startup+0x396): undefined reference to `flint_abort'
collect2: error: ld returned 1 exit status
make[1]: *** [../build/fmpr/test/t-abs_bound_le_2exp_fmpz] Error 1
make[1]: Leaving directory `/home/therickaman/libs/arb/arb/fmpr'

I decided to verify that flint_abort was missing from the flint source code by issuing grep -R flint_abort ./ from within the source code directory for flint.  It returned no instances of flint_abort.

NOTE:  Cloning from Fredrick's git repository of flint makes this work, but not Bill Hart's flint repository.

**Comment by fredrik-johansson** [comment]
It should be  in Bill's repository too... can you double check that you have the right version built?

However, I see now that flint_abort is not in the latest release of flint, and we need to support that.

@thofma can you think of a good solution? I think maybe the easiest thing would be to add a #define HAVE_FLINT_ABORT in flint.h and then check for this in Arb, aliasing flint_abort to abort if it's not present.

**Comment by thofma** [comment]
Strange, flint_abort is definitely in Bill's repository.

@fredrik-johansson Your solution does sound good. But we should ask @wbhart if he knows an alternative solution.

**Comment by wbhart** [comment]
You can probably check the flint version. We could change that to 2.6.0 in our repositories and then you can check for 2.6.0.

**Comment by fredrik-johansson** [comment]
Yes, increasing the version number ought to work.

It's going to break for anyone who has an old git checkout of flint with version number 2.5 and flint_abort defined. But that can't be helped.

**Comment by wbhart** [comment]
I changed it to 2.5.3 in my repo, the reasoning being that if someone finds
a severe issue in Flint that we need to issue a patch release for urgently,
we'll want to use the 2.5.3 not the 2.6.0. The effect should be the same
for Arb, which will just check if the version is >= 2.5.3.

**Comment by fredrik-johansson** [comment]
What is the correct way to compare version numbers?

**Comment by wbhart** [comment]
FLINT_RELEASE > 20502

**Comment by wbhart** [comment]
Or even better (since it is correct):

__FLINT_RELEASE > 20502

**Comment by thofma** [comment]
I am currently looking into it, @fredrik-johansson

**Comment by rickyefarr** [comment]
> It should be in Bill's repository too... can you double check that you have the right version built?

I am very sorry for the confusion.  Yes, it is in his repository.  I just could not get his to pass all the tests.  I just saw two failures and assumed that it was from the same issue.  I'll report on the issue I am having with that library soon.
