### ISSUE TITLE
Riemann theta function [wishlist]

### ISSUE THREAD

**Issue by videlec** [flintlib/arb#201]
The [Riemann theta function](https://en.wikipedia.org/wiki/Theta_function#Riemann_theta_function) is a natural generalization of the Jacobi theta functions. In this more general situation, the invariance involves the integral symplectic group acting on the Siegel half space (there is no nice fundamental domain, though there are some good super sets: the so called "Siegel domains").

An arbitrary precision implementation would be very useful for Riemann surface computations (see e.g. [issue 150 in abelfunctions](https://github.com/abelfunctions/abelfunctions/issues/150)).

**Comment by fredrik-johansson** [comment]
This would certainly be useful, but I'm not familiar with the algorithms. Are you interested in helping out with an implementation?

**Comment by videlec** [comment]
Of course!

For future references

- Deconinck et al "Computing Riemann Theta Functions"  (2004)
- entry in [DLMF](http://dlmf.nist.gov/21)
- Deconinck, Swierczewski "Computing Riemann theta functions in Sage with applications" (2016)

**Comment by tthsqe12** [comment]
I also think this would be useful, but it will be a lot of work.

**Comment by tthsqe12** [comment]
I believe that adding this function to this c library would add a considerable amount of bloat. A core algorithm is Cholesky decomposition. Is this already present in arb?

**Comment by fredrik-johansson** [comment]
Done in Flint.
