### ISSUE TITLE
libflint-arb

### ISSUE THREAD

**Issue by MacroUniverse** [flintlib/arb#253]
Hi,
I used "apt-get" to install "libflint-arb-dev". However, it is not clear in the [documentation](http://arblib.org/#) how to use it.
After hours of struggling, I found out I need something like "g++ test.cpp -lflint-arb -lflint" instead of just "-larb".
It will be nice to point that out in the documentation.

**Comment by fredrik-johansson** [comment]
Hmm, I was not actually aware that Debian had renamed the library and not just the package. That's a bit annoying really.

**Comment by fredrik-johansson** [comment]
Added a note in 5f47856c668788f9948d56229a07c18ee6909c9c
