### ISSUE TITLE
The function n_gcd_full isn't there anymore in flint 2.9.0 beta1

### ISSUE THREAD

**Issue by SnarkBoojum** [flintlib/arb#420]
In flint 2.6.0, n_gcd_full was deprecated and is now removed.

You just need to s/n_gcd_full/n_gcd/ in acb_modular/hilbert_class_poly.c and arb_fmpz_poly/gauss_period_minpoly.c to get rid of the problem.

**Comment by fredrik-johansson** [comment]
This is already fixed in master. There will be a new Arb release shortly following the new Flint.

**Comment by SnarkBoojum** [comment]
If it's possible to have a good arb before the next flint, that's better.

You're too focused on sagemath where each new version will change flint+arb in a single stroke : all other distributions will go with the flow: see the new flint, package it, see it breaks arb, report here...

**Comment by fredrik-johansson** [comment]
We should maybe put back n_gcd_full in Flint until 2.10 just so that there are minimal issues.

**Comment by albinahlback** [comment]
Or perphaps it shouldn't compile if you have a lower version?
